### ISSUE TITLE
JS Not Loaded on GitHub Enterprise

### ISSUE THREAD

**Issue by rianrainey** [Yatser/prettypullrequests#43] opened 2016-09-20 02:23 UTC
First of all, great plugin!

This worked well for me for a couple weeks and now I'm unable to get the js to load on GH enterprise pages. It works as expected on non-GHE pages.

I've disabled all other plugins and I still can't get GHE PR files to toggle. When I use the dev tools inspector I can see that the plugin never loads its js/css. However, regular GH pages load the js/css correctly.

I get prompted for new permissions when I enter the GHE url in the options, but I see no change in functionality. I'm wondering if other GHE users have experienced recent degradation.

Thanks for any help. This plugin helps very well w/ managing PRs.

**Comment by rianrainey** [comment] 2016-09-20 02:35
Checked sha: c6f02dd1e5c29dfc5e0a8e9107b9e23916fc91c2 and it works correctly for me. 4fd610ff8f0db2ca68af6a705e3fcaaec6d468ed broke GHE support. b4b3c267a3224f42d263f64a58484d4ceaab5c15 did not restore GHE functionality for me. Hope this helps somebody else.

**Comment by Yatser** [comment] 2016-09-20 15:11
Thanks @rianrainey, I was able to test the prompting for new permissions, but I was unable to test the content script being loaded and working properly because I don't have github enterprise. It is pretty simple code, especially given that the permissions are being requested... would you care to take a shot at a PR to solve this issue?

It does have the potential to turn into something much more difficult... as maybe we can't conditionally load the content script based on the optional permissions... we'll have to see. If you don't think you can figure it out or don't care to, I will certainly attempt to fix it, but I won't be able to look at it for a week as I'm about to leave on holidays.

Thanks for logging the bug!

**Comment by lzelevinsky** [comment] 2016-10-07 15:37
Same thing for me too - the app used to work for me and stopped working on github enterprise

**Comment by Yatser** [comment] 2016-10-07 15:41
OK, as I mentioned, I was able to test that the permissions prompting still works, but I will either have to get creative to see if I can find out how to fix the rest, or accept a PR from someone who uses github enterprise (which is how this extension ended up supporting enterprise in the first place).

It looks like I can start a free trial of enterprise... so that could be an option for me.

**Comment by lzelevinsky** [comment] 2016-10-07 15:49
I'm happy to try something sometime, but don't have any experience with developing chrome extensions, so would need to climb the learning curve a bit.

**Comment by Yatser** [comment] 2016-10-31 15:24
I finally started looking into this this weekend. I believe the problem is that the content script is never told to load. Since switching to the optional permissions, the content script would have to be programatically injected into those pages, and I'm not seeing that happen anywhere.

I have what SHOULD be the fix in place but it wasn't quite working and I ran out of time... but it should be fixable from here, and I shouldn't have to widen any permissions which is great.

**Comment by lzelevinsky** [comment] 2016-10-31 22:10
:+1:

**Comment by Yatser** [comment] 2016-11-02 01:21
Hey all,

I just pushed up version 2.10.1 that SHOULD address this issue. I tested it using my own trial version of Github Enterprise, and found several issues that I addressed. I also found even more corner cases and bugs of how the plugin loads, but those are somewhat unrelated to Github Enterprise and more to github's mixed use of full page reloads and client templating. 

I am going to do a complete rewrite of this extension soon (I was hoping the need for this extension would have died soon after, but Github apparently has no interest in adding it), so I'll address the corner bugs then, but GHE functionality SHOULD be returned.

Can you guys test it and let me know... and if we are good I'll close the bug!

**Comment by lzelevinsky** [comment] 2016-11-02 01:37
Will do! 2.10.1 not showing up in the store for me yet.

Very much appreciate your work on this - thanks. I miss the collapsing files functionality every day :).

**Comment by lzelevinsky** [comment] 2016-11-02 02:17
Got latest version.

Collapsing / expanding files works - which is awesome and is mostly what I wanted.

The checkboxes to show/hide added and deleted lines are there but don't work.

Tried them on github.com and they work fine but not on the enterprise page - checking and unchecking them doesn't do anything that I can see.

Thanks a lot.

**Comment by Nilegfx** [comment] 2016-12-15 22:06
It had this issue with Version: 2.10.3

An easier solution is to do the following: 
* install the extension
* add your GHE URL
* go to chrome extensions page
* disable the extension and enable it back again

**Comment by Yatser** [comment] 2016-12-18 20:51
Hey @lzelevinsky, sorry, I somehow missed your comment about the checkboxes. I assume they are still not working?

I just removed my github enterprise VM a few days ago too, ugh, and my free trial is probably over. I probably won't fix this feature soon, but I will try and fix it sometime after the holidays. Thanks for letting me know!

**Comment by gholtslander-va** [comment] 2017-01-22 20:30
If one of you with GitHub Enterprise wants to try out the changes in #47 , that'd be awesome.

@Nilegfx @lzelevinsky @rianrainey ?

**Comment by gholtslander-va** [comment] 2017-05-03 14:19
Oh boy. Yeah that's a typo.

**Comment by gholtslander-va** [comment] 2017-05-03 14:59
@rianrainey I fixed that, if you'd like to try again.

**Comment by Yatser** [comment] 2017-05-04 14:51
As soon as he confirms it, we can get it into the released version!

**Closed** 2017-08-19 18:10 UTC
